# Setup
title:               yao-ge
tagline:             'Hey There🙋'
description:         'Some scattered jottings'
url:                 https://yao-ge.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y

github:
  repo: https://github.com/yao-ge
